language: node_js
services:
  - docker
sudo: required
node_js:
  - "node"

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - npm install -D jest
  - npm install
branches:
  only:
    - master
    
before_script: 
  - cd  ./api/customers
  - chmod 777 ./node_modules/.bin/jest
  - ls
script:
  - docker build -t nitikornchumnankul/customers . 
  - docker push nitikornchumnankul/customers:v1.1.2

notifications:
    slack: nitikornproject1:gdCBIXPs27fHWBz4Ymomk5JC